name: Tag & Release

on:
  workflow_dispatch:
    inputs:
      package:
        type: choice
        description: 'If not specified, all packages will be released.'
        options:
          - ""
          - ros_gz_interfaces
          - ros_gz_bridge

jobs:
  release_amd:
    name: Release AMD
    runs-on: buildjet-2vcpu-ubuntu-2204

    steps:
      - name: Checkout this repository
        uses: actions/checkout@v3

      - name: Semantic release
        uses: Greenroom-Robotics/ros_semantic_release_action@main
        with:
          token: ${{ secrets.API_TOKEN_GITHUB }}
          package: ${{ github.event.inputs.package }}
          arch: amd64
          public: true
          changelog: false

  # release_arm:
  #   name: Release ARM
  #   runs-on: buildjet-8vcpu-ubuntu-2204-arm

  #   steps:
  #     - name: Checkout this repository
  #       uses: actions/checkout@v3

  #     - name: Semantic release
  #       uses: Greenroom-Robotics/ros_semantic_release_action@main
  #       with:
  #         token: ${{ secrets.API_TOKEN_GITHUB }}
  #         package: ${{ github.event.inputs.package }}
  #         arch: arm64
  #         public: true
  #         changelog: false
